<?php
// Layout: Gradient Stats Section
if (!function_exists('acf_add_local_field_group')) {
    return [];
}

return [
    'key' => 'layout_gradient_stats',
    'name' => 'gradient_stats',
    'label' => 'Bloc chiffres (dégradé)',
    'display' => 'block',
    'sub_fields' => [
        [
            'key' => 'field_gradient_stats_color_start',
            'label' => 'Dégradé - Couleur de début (gauche)',
            'name' => 'color_start',
            'type' => 'color_picker',
            'wrapper' => ['width' => '50'],
        ],
        [
            'key' => 'field_gradient_stats_color_end',
            'label' => 'Dégradé - Couleur de fin (droite)',
            'name' => 'color_end',
            'type' => 'color_picker',
            'wrapper' => ['width' => '50'],
        ],
        [
            'key' => 'field_gradient_stats_bg_split_top',
            'label' => 'Fond pleine largeur – Couleur haute (0% - 50%)',
            'name' => 'background_split_top',
            'type' => 'color_picker',
            'instructions' => 'Optionnel. Avec la couleur basse, crée un fond bi-couleur vertical derrière la carte.',
            'wrapper' => ['width' => '50'],
        ],
        [
            'key' => 'field_gradient_stats_bg_split_bottom',
            'label' => 'Fond pleine largeur – Couleur basse (50% - 100%)',
            'name' => 'background_split_bottom',
            'type' => 'color_picker',
            'instructions' => 'Optionnel. Affichée seulement si la couleur haute est définie.',
            'wrapper' => ['width' => '50'],
        ],
        [
            'key' => 'field_gradient_stats_heading',
            'label' => 'Titre (H2)',
            'name' => 'heading',
            'instructions' => 'Texte simple uniquement.  Vous pouvez ajouter une mise en forme &lt;span&gt;texte mis en forme&lt;/span&gt; dans le contenu final si nécessaire.',
            'type' => 'text',
            'required' => 0,
            'wrapper' => ['width' => '50'],
        ],
        // New: global timing controls
        [
            'key' => 'field_gradient_stats_duration_ms',
            'label' => 'Durée par compteur (ms)',
            'name' => 'duration_ms',
            'type' => 'number',
            'default_value' => 1600,
            'min' => 200,
            'step' => 50,
            'wrapper' => ['width' => '50'],
        ],
        [
            'key' => 'field_gradient_stats_stagger_ms',
            'label' => 'Délai incrémental entre compteurs (ms)',
            'name' => 'stagger_ms',
            'type' => 'number',
            'default_value' => 120,
            'min' => 0,
            'step' => 10,
            'wrapper' => ['width' => '50'],
            'instructions' => 'Appliqué par rang (0, 1×, 2×, ...) si pas de délai saisi au niveau de l\'item.'
        ],
        [
            'key' => 'field_gradient_stats_items',
            'label' => 'Chiffres',
            'name' => 'stats',
            'type' => 'repeater',
            'layout' => 'row',
            'button_label' => 'Ajouter un chiffre',
            'min' => 3,
            'max' => 4,
            'sub_fields' => [
                [
                    'key' => 'field_gradient_stats_item_icon',
                    'label' => 'Picto (optionnel)',
                    'name' => 'icon',
                    'type' => 'image',
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'wrapper' => ['width' => '20'],
                ],
                [
                    'key' => 'field_gradient_stats_item_prefix',
                    'label' => 'Préfixe (optionnel)',
                    'name' => 'prefix',
                    'type' => 'text',
                    'wrapper' => ['width' => '20'],
                ],
                [
                    'key' => 'field_gradient_stats_item_value',
                    'label' => 'Valeur',
                    'name' => 'value',
                    'type' => 'text',
                    'required' => 1,
                    'wrapper' => ['width' => '30'],
                ],
                [
                    'key' => 'field_gradient_stats_item_label',
                    'label' => 'Libellé',
                    'name' => 'label',
                    'type' => 'text',
                    'required' => 1,
                    'wrapper' => ['width' => '30'],
                ],
                [
                    'key' => 'field_gradient_stats_item_delay',
                    'label' => 'Délai de départ (ms)',
                    'name' => 'delay',
                    'type' => 'number',
                    'instructions' => 'Laisser vide pour utiliser le décalage automatique (stagger).',
                    'min' => 0,
                    'step' => 10,
                    'wrapper' => ['width' => '10'],
                ],
                [
                    'key' => 'field_gradient_stats_item_duration',
                    'label' => 'Durée de l\'animation (ms)',
                    'name' => 'duration',
                    'type' => 'number',
                    'instructions' => 'Sinon, la durée globale s\'applique.',
                    'min' => 200,
                    'step' => 50,
                    'wrapper' => ['width' => '10'],
                ],
            ],
        ],
    ],
];
