<?php
// Layout: Masonry Gallery (4 -> 2 columns)
if (!function_exists('acf_add_local_field_group')) {
    return [];
}

return [
    'key' => 'layout_masonry_gallery',
    'name' => 'masonry_gallery',
    'label' => 'Galerie Masonry',
    'display' => 'block',
    'sub_fields' => [
        [
            'key' => 'field_masonry_heading',
            'label' => 'Titre (H2)',
            'name' => 'heading',
            'type' => 'text',
            'instructions' => 'Texte simple uniquement.  Vous pouvez ajouter une mise en forme &lt;span&gt;texte mis en forme&lt;/span&gt; dans le contenu final si nécessaire.',
            'wrapper' => ['width' => '50'],
        ],
        [
            'key' => 'field_masonry_description',
            'label' => 'Description',
            'name' => 'description',
            'type' => 'textarea',
            'rows' => 3,
            'new_lines' => '',
            'wrapper' => ['width' => '50'],
        ],
        [
            'key' => 'field_masonry_primary_btn',
            'label' => 'Bouton principal',
            'name' => 'primary_button',
            'type' => 'group',
            'layout' => 'block',
            'wrapper' => ['width' => '50'],
            'sub_fields' => [
                [
                    'key' => 'field_masonry_primary_btn_label',
                    'label' => 'Libellé',
                    'name' => 'label',
                    'type' => 'text',
                    'wrapper' => ['width' => '50'],
                ],
                [
                    'key' => 'field_masonry_primary_btn_link',
                    'label' => 'Page interne',
                    'name' => 'link',
                    'type' => 'page_link',
                    'post_type' => [],
                    'allow_null' => 1,
                    'allow_archives' => 0,
                    'multiple' => 0,
                    'wrapper' => ['width' => '50'],
                ],
            ],
        ],
        [
            'key' => 'field_masonry_secondary_btn',
            'label' => 'Bouton secondaire',
            'name' => 'secondary_button',
            'type' => 'group',
            'layout' => 'block',
            'wrapper' => ['width' => '50'],
            'sub_fields' => [
                [
                    'key' => 'field_masonry_secondary_btn_label',
                    'label' => 'Libellé',
                    'name' => 'label',
                    'type' => 'text',
                    'wrapper' => ['width' => '50'],
                ],
                [
                    'key' => 'field_masonry_secondary_btn_link',
                    'label' => 'Page interne',
                    'name' => 'link',
                    'type' => 'page_link',
                    'post_type' => [],
                    'allow_null' => 1,
                    'allow_archives' => 0,
                    'multiple' => 0,
                    'wrapper' => ['width' => '50'],
                ],
            ],
        ],
        [
            'key' => 'field_masonry_bg_color',
            'label' => 'Couleur de fond',
            'name' => 'background_color',
            'type' => 'color_picker',
            'default_value' => '#ffffff',
            'wrapper' => ['width' => '50'],
        ],
        [
            'key' => 'field_masonry_images',
            'label' => 'Images',
            'name' => 'images',
            'type' => 'repeater',
            'layout' => 'table',
            'button_label' => 'Ajouter une image',
            'min' => 2,
            'sub_fields' => [
                [
                    'key' => 'field_masonry_item_image',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'required' => 1,
                ],
                [
                    'key' => 'field_masonry_item_caption',
                    'label' => 'Légende (optionnel)',
                    'name' => 'caption',
                    'type' => 'text',
                    'instructions' => 'Texte court affiché sur l’image (optionnel).',
                ],
                [
                    'key' => 'field_masonry_item_overlay_color',
                    'label' => 'Couleur d’overlay (optionnel)',
                    'name' => 'overlay_color',
                    'type' => 'color_picker',
                    'default_value' => '#0a84eb',
                    'instructions' => 'Couleur de l’overlay appliqué au survol/affichage (optionnel).',
                ],
            ],
        ],
        [
            'key' => 'field_masonry_emojis',
            'label' => 'Emojis',
            'name' => 'emojis',
            'type' => 'gallery',
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'insert' => 'append',
            'instructions' => 'Images globales “emojis” (optionnel, illimité).',
        ],
    ],
];
