<?php
// Layout: Contact Form (left content + repeater infos, right CF7 form)
if (!function_exists('acf_add_local_field_group')) {
    return [];
}

return [
    'key' => 'layout_contact_form',
    'name' => 'contact-form',
    'label' => 'Contact – Formulaire',
    'display' => 'block',
    'sub_fields' => [
        [
            'key' => 'field_contact_bg_color',
            'label' => 'Couleur de fond',
            'name' => 'background_color',
            'type' => 'color_picker',
            'default_value' => '',
            'wrapper' => ['width' => '50'],
        ],
        [
            'key' => 'field_contact_heading',
            'label' => 'Titre',
            'name' => 'heading',
            'type' => 'text',
            'required' => 1,
            'instructions' => 'Vous pouvez ajouter une mise en forme &lt;span&gt;texte mis en forme&lt;/span&gt; dans le contenu final si nécessaire.',
            'wrapper' => ['width' => '50'],
        ],
        [
            'key' => 'field_contact_title_is_h1',
            'label' => 'Rendre le titre en H1',
            'name' => 'title_is_h1',
            'type' => 'true_false',
            'ui' => 1,
            'default_value' => 0,
            'wrapper' => ['width' => '50'],
        ],
        [
            'key' => 'field_contact_description',
            'label' => 'Sous-titre',
            'name' => 'description',
            'type' => 'textarea',
            'rows' => 3,
            'new_lines' => '',
            'wrapper' => ['width' => '50'],
        ],
        [
            'key' => 'field_contact_cf7',
            'label' => 'Formulaire Contact Form 7',
            'name' => 'contact_form',
            'type' => 'post_object',
            'post_type' => ['wpcf7_contact_form'],
            'return_format' => 'id',
            'ui' => 1,
            'required' => 1,
            'wrapper' => ['width' => '50'],
        ],
        // Fields for "Cards" layout
        [
            'key' => 'field_contact_card_appointment_text_color',
            'label' => 'Couleur de texte (Carte Rendez-vous)',
            'name' => 'card_appointment_text_color',
            'type' => 'color_picker',
            'default_value' => '#ffffff',
            'wrapper' => ['width' => '50'],
        ],
        [
            'key' => 'field_contact_card_appointment_icon',
            'label' => 'Icône (Carte Rendez-vous)',
            'name' => 'card_appointment_icon',
            'type' => 'image',
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
        ],
        [
            'key' => 'field_contact_card_appointment_title',
            'label' => 'Titre (Carte Rendez-vous)',
            'name' => 'card_appointment_title',
            'type' => 'text',
            'default_value' => 'Planifions un rendez-vous',
        ],
        [
            'key' => 'field_contact_card_appointment_text',
            'label' => 'Texte (Carte Rendez-vous)',
            'name' => 'card_appointment_text',
            'type' => 'textarea',
            'rows' => 3,
        ],
        [
            'key' => 'field_contact_card_appointment_cta',
            'label' => 'Bouton (Carte Rendez-vous)',
            'name' => 'card_appointment_cta',
            'type' => 'link',
        ],
        [
            'key' => 'field_contact_card_appointment_cta_id',
            'label' => 'ID du Bouton (Carte Rendez-vous)',
            'name' => 'card_appointment_cta_id',
            'type' => 'text',
            'instructions' => 'Identifiant unique pour le suivi ou le CSS (optionnel)',
        ],
        [
            'key' => 'field_contact_card_location_bg_color',
            'label' => 'Couleur de fond (Carte Localisation)',
            'name' => 'card_location_bg_color',
            'type' => 'color_picker',
            'default_value' => '#ffffff',
            'wrapper' => ['width' => '50'],
        ],
        [
            'key' => 'field_contact_card_location_title',
            'label' => 'Titre (Carte Localisation)',
            'name' => 'card_location_title',
            'type' => 'text',
            'default_value' => 'Venir à l’agence',
        ],
        [
            'key' => 'field_contact_card_location_text',
            'label' => 'Texte (Carte Localisation)',
            'name' => 'card_location_text',
            'type' => 'textarea',
            'rows' => 3,
        ],
        [
            'key' => 'field_contact_card_location_phone',
            'label' => 'Téléphone (Carte Localisation)',
            'name' => 'card_location_phone',
            'type' => 'text',
            'default_value' => '03 87 10 18 50',
        ],
        [
            'key' => 'field_contact_card_location_address',
            'label' => 'Adresse (Carte Localisation)',
            'name' => 'card_location_address',
            'type' => 'textarea',
            'rows' => 2,
            'default_value' => '104 rue Hochfelden, 67200 Strasbourg',
        ],
        [
            'key' => 'field_contact_card_location_map_link',
            'label' => 'Lien Carte (Carte Localisation)',
            'name' => 'card_location_map_link',
            'type' => 'link',
        ],
    ],
];
